
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: pages
    output: true


title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll



# Manifest settings (Used to make manifest.json)
manifest_short_name: Short Name # Appears in "Add to home screen" dialogues
manifest_lang: en
manifest_background_color: #303F9F
manifest_short_name: tmm
manifest_display: standalone

header-img: img/i-rest.jpg

# You can find your shortname on the Settings page of your Disqus account
disqus: https-tellmemore-life

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-93038764-7


pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
    - offline.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"


markdown: kramdown
highlighter: rouge
permalink: "/:title"
paginate: 10
exclude:
- less
- google29b6354e114fc919.html
- node_modules
- Gruntfile.js
- package.json
- CNAME
- README.md
gems:
- jekyll-paginate
- jekyll-pwa-plugin


plugins: 
 - jekyll-paginate 
