collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: pages
    output: true
title: My  awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
manifest_short_name: tmm
manifest_lang: en
manifest_background_color: null
manifest_display: standalone
header-img: img/i-rest.jpg
disqus: https-tellmemore-life
google_analytics: UA-93038764-7
markdown: kramdown
highlighter: rouge
permalink: '/:title'
paginate: 10
exclude:
  - less
  - google29b6354e114fc919.html
  - node_modules
  - Gruntfile.js
  - package.json
  - CNAME
  - README.md
gems:
  - jekyll-paginate
  - jekyll-pwa-plugin
plugins:
  - jekyll-paginate
